import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblEmail: String = "Email"
    static let kLblLastName2: String = "Last Name"
    static let kLblJennyWilson: String = "Jenny Wilson"
    static let kMsgCorduroySunset: String = "Corduroy sunset of Italy"
    static let kLblUse: String = "Use"
    static let kLblArianaGrinder: String = "Ariana Grinder"
    static let kMsgPleaseEnterTh: String =
        "Please enter the 4 digit code sent to yourmail@example.com"
    static let kLblWest: String = "West"
    static let kLblNext: String = "Next"
    static let kMsgMyTripToTurk: String = "My trip to Turkey"
    static let kLblLastName: String = "Last name"
    static let kMsgAccountGmailC: String = "Account@gmail.com"
    static let kLblApple: String = "Apple"
    static let kMsgDarleneRoberts: String = "Darlene Robertson"
    static let kMsgYahooYouHave: String = "Yahoo! You have successfully verified \nthe account."
    static let kMsgPleaseFillYou: String = "Please fill your informations"
    static let kMsgLeslieAlexande: String = "Leslie Alexander"
    static let kLblGoogle: String = "Google"
    static let kLblFirstName: String = "First name"
    static let kLblAfrica: String = "Africa"
    static let kLblItaly: String = "Italy"
    static let kLblFirstName2: String = "First Name"
    static let kLblSignInNow: String = "Sign in now"
    static let kLblEgypt: String = "Egypt"
    static let kMsgSearchCountry: String = "Search country or list"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblSignIn: String = "Sign in"
    static let kLblTurkey: String = "Turkey"
    static let kMsgMyTripToChin: String =
        "My trip to China started in Beijing, where I stayed in a beautiful hotel called ..."
    static let kLblOpenEmail: String = "Open email"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblWelcomeBack: String = "Welcome back"
    static let kLblChooseYour: String = "Choose your"
    static let kMsgTravelToAfric: String = "Travel to Africa"
    static let kLblSignUp: String = "Sign up"
    static let kLblPassword: String = "Password"
    static let kLblSuccessfully: String = "Successfully"
    static let kLblFacebook: String = "Facebook"
    static let kLblNewArticles: String = "New Articles"
    static let kLblWellcome: String = "Wellcome!"
    static let kMsgSelectLoginMe: String = "Select login method"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblVerifyEmail: String = "Verify email"
    static let kLblDone: String = "Done"
}
